### ISSUE TITLE
go-gtk panics at runtime when compiled with Go 1.6 over passing pointer to C code

### ISSUE THREAD

**Issue by andreastt** [mattn/go-gtk#266]
go-gtk builds fine on Go 1.6, but panics at runtime when compiled with Go 1.6. It does this because it passes a Go pointer through cgo to C code, and this has been disallowed to improve garbage collector efficiency, as far as I understand.

As a temporary workaround it is possible to set the environment variable `GODEBUG=cgocheck=0`.

```go
package main

import "github.com/mattn/go-gtk/gtk"
import "os"

func main() {
	gtk.Init(&os.Args)
	gtk.Main()
}
```

Output:

```
% ./killer
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x57f040, 0xc8200721d0)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/mattn/go-gtk/gtk._cgoCheckPointer0(0x549960, 0xc8200820a0, 0xc8200721c0, 0x1, 0x1, 0xc820072184)
	??:0 +0x4d
github.com/mattn/go-gtk/gtk.Init(0x8a6980)
	/home/ato/1/src/github.com/mattn/go-gtk/gtk/gtk.go:228 +0x3fd
main.main()
	/home/ato/1/src/github.com/andreastt/killer/main.go:7 +0x23
```

This behaviour was allowed in Go 1.5 and earlier, and is further explained in [Go 1.6’s release notes](https://golang.org/doc/go1.6#cgo).

**Comment by mattn** [comment]
should be fixed.

**Comment by andreastt** [comment]
@mattn I’m not sure this is fixed. Following f8831fa, I get a different runtime stacktrace irregardless of `GODEBUG=cgocheck=0`:

```
% make
…
% cd example
% make
…
% ./demo/demo 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x80 addr=0x0 pc=0x7f3cc297843d]

runtime stack:
runtime.throw(0x76ca00, 0x2a)
        /usr/lib/go/src/runtime/panic.go:530 +0x90
runtime.sigpanic()
        /usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5dbc90, 0xc820049b58, 0x100000000000000)
        /usr/lib/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820049b20 sp=0xc820049af0
github.com/mattn/go-gtk/gtk._Cfunc_gtk_init(0xc82000a2dc, 0xddeea0)
        ??:0 +0x36 fp=0xc820049b58 sp=0xc820049b20
github.com/mattn/go-gtk/gtk.Init(0xb16790)
        /home/ato/1/src/github.com/mattn/go-gtk/gtk/gtk.go:230 +0x1ee fp=0xc820049c40 sp=0xc820049b58
main.main()
        /home/ato/1/src/github.com/mattn/go-gtk/example/demo/demo.go:49 +0x32 fp=0xc820049f50 sp=0xc820049c40
runtime.main()
        /usr/lib/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820049fa0 sp=0xc820049f50
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820049fa8 sp=0xc820049fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1
```

**Comment by subfuzion** [comment]
I can confirm same error with:

go version go1.6.2 linux/amd64
Linux 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nixuw** [comment]
same error at go1.7.1 darwin/amd64

**Comment by mattn** [comment]
dup https://github.com/mattn/go-gtk/issues/263
