### ISSUE TITLE
About dialog: only one tab in "Thanks" dialog is allowed with AboutDialog.SetLogo()

### ISSUE THREAD

**Issue by pztrn** [mattn/go-gtk#282]
I'm trying to add "Authors" and "Artists" tab in about dialog, and got panic:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f641b9a64c6]

runtime stack:
runtime.throw(0x769c25, 0x2a)
	/usr/lib/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x629050, 0xc420053720, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:131 +0x110 fp=0xc4200536f0 sp=0xc4200536b0
github.com/mattn/go-gtk/gtk._Cfunc_gtk_about_dialog_set_documenters(0x12bc190, 0x10ce190)
	??:0 +0x41 fp=0xc420053720 sp=0xc4200536f0
github.com/mattn/go-gtk/gtk.(*AboutDialog).SetDocumenters(0xc420014e70, 0xc420014e90, 0x1, 0x1)
	/data/.go/src/github.com/mattn/go-gtk/gtk/gtk.go:1624 +0x243 fp=0xc420053798 sp=0xc420053720
runtime.call32(0xc420010de0, 0x7867e8, 0xb91ac8, 0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:479 +0x4c fp=0xc420053850 sp=0xc420053820
reflect.Value.call(0x6fb320, 0x7867e8, 0x13, 0x7608c1, 0x4, 0xb91ac8, 0x0, 0x0, 0xc42001e3c0, 0x71a160, ...)
	/usr/lib/go/src/reflect/value.go:434 +0x5c8 fp=0xc420053ba0 sp=0xc420053850
reflect.Value.Call(0x6fb320, 0x7867e8, 0x13, 0xb91ac8, 0x0, 0x0, 0x46c7ec, 0x0, 0x470c50)
	/usr/lib/go/src/reflect/value.go:302 +0xa4 fp=0xc420053c08 sp=0xc420053ba0
github.com/mattn/go-gtk/glib._go_glib_callback(0x1127870)
	/data/.go/src/github.com/mattn/go-gtk/glib/glib.go:758 +0x11e fp=0xc420053c90 sp=0xc420053c08
github.com/mattn/go-gtk/glib._cgoexpwrap_b00a5877f6a0__go_glib_callback(0x1127870)
	??:0 +0x2b fp=0xc420053ca8 sp=0xc420053c90
runtime.call32(0x0, 0x7fffef65c568, 0x7fffef65c600, 0x8)
	/usr/lib/go/src/runtime/asm_amd64.s:479 +0x4c fp=0xc420053cd8 sp=0xc420053ca8
runtime.cgocallbackg1(0x0)
	/usr/lib/go/src/runtime/cgocall.go:283 +0x19d fp=0xc420053d50 sp=0xc420053cd8
runtime.cgocallbackg(0x0)
	/usr/lib/go/src/runtime/cgocall.go:170 +0x84 fp=0xc420053db8 sp=0xc420053d50
runtime.cgocallback_gofunc(0x445d88, 0x62cd30, 0xc420053e50, 0xb772e0)
	/usr/lib/go/src/runtime/asm_amd64.s:728 +0x74 fp=0xc420053dd8 sp=0xc420053db8
runtime.asmcgocall(0x62cd30, 0xc420053e50)
	/usr/lib/go/src/runtime/asm_amd64.s:575 +0x42 fp=0xc420053de0 sp=0xc420053dd8
runtime.cgocall(0x62cd30, 0xc420053e50, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:132 +0x128 fp=0xc420053e20 sp=0xc420053de0
github.com/mattn/go-gtk/gtk._Cfunc_gtk_main()
	??:0 +0x41 fp=0xc420053e50 sp=0xc420053e20
github.com/mattn/go-gtk/gtk.Main()
	/data/.go/src/github.com/mattn/go-gtk/gtk/gtk.go:248 +0x14 fp=0xc420053e58 sp=0xc420053e50
runtime.main()
	/usr/lib/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420053fa0 sp=0xc420053f48
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420053fa8 sp=0xc420053fa0
```
(Removed my app name in sake of NDA, sorry).

Here's example code that cause the issue:

```go
func ShowAboutDialog() {
    ad := gtk.NewAboutDialog()

    ad.SetProgramName("TheProgram")
    ad.SetComments("TheDescription")
    ad.SetVersion("0.1")
    ad.SetWebsite("http://somewebsite.com")
    ad.SetLogo(logo)

    // ToDo: put it in plain text files.
    var authors []string
    authors = append(authors, "I AM THE AUTHOR, HWEHEHE")
    ad.SetAuthors(authors)

    var artists []string
    artists = append(artists, "I AM THE ONLY ARTIST!")
    ad.SetArtists(artists)

    ad.SetCopyright("WHO NEEDS COPYRIGHT HERE")
    ad.SetLicense("NDA!")

    ad.ShowAll()
}
```

Regarding example code and ``github.com/mattn/go-gtk/gtk.(*AboutDialog).SetDocumenters`` - any call for creating more than one tab (SetArtists, SetDocumenters, etc.) cause application crash.

And very interesting part - when I comment out ``ad.SetLogo(logo)`` (which is *gdkpixbuf.Pixbuf) - everything is normal now and I can add more than one tab here.

So is this go-gtk problem, or GTK+2 itself?

**Comment by mattn** [comment]
example/demo works fine on your environemnt?

**Comment by pztrn** [comment]
Nope. Traceback:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f81e024f6c0]

runtime stack:
runtime.throw(0x6472ad, 0x2a)
	/usr/lib/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5c0220, 0xc420053cb8, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420053c88 sp=0xc420053c48
github.com/mattn/go-gtk/gtk._Cfunc_gtk_init(0xc42000c348, 0xc42000c380)
	??:0 +0x41 fp=0xc420053cb8 sp=0xc420053c88
github.com/mattn/go-gtk/gtk.Init(0x9e6d70)
	/data/.go/src/github.com/mattn/go-gtk/gtk/gtk.go:230 +0x19e fp=0xc420053d48 sp=0xc420053cb8
main.main()
	/data/.go/src/github.com/mattn/go-gtk/example/demo/demo.go:49 +0x42 fp=0xc420053f48 sp=0xc420053d48
runtime.main()
	/usr/lib/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420053fa0 sp=0xc420053f48
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420053fa8 sp=0xc420053fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1
```

**Comment by pztrn** [comment]
Tried other examples - they're crashing with exactly same traceback.

I'm in Gentoo with GTK2.24.30 and Go 1.7

**Comment by mattn** [comment]
Try to pass nil into gtk.Init(nil).

**Comment by pztrn** [comment]
Yep, that worked, and every element in demo works too, including About window. Tried in my application - and all ok here too.

**Comment by pztrn** [comment]
Okay, encountered same thing with my URTrator, see https://github.com/pztrn/urtrator/blob/master/ui/about.go. All works on Linux, on macOS and Windows I got app crash with this traceback:

```
Exception 0xc0000005 0x0 0xffffffffffffffff 0x7ffba3b511d0
PC=0x7ffba3b511d0
signal arrived during external code execution

github.com/mattn/go-gtk/gtk._Cfunc_gtk_about_dialog_set_artists(0x4afde90, 0x4afbc70)
        ??:0 +0x48
github.com/mattn/go-gtk/gtk.(*AboutDialog).SetArtists(0xc0423a5450, 0xc0423a5470, 0x1, 0x1)
        C:/msys64/home/pztrn/GOPATH/src/github.com/mattn/go-gtk/gtk/gtk.go:1602 +0x24a
github.com/pztrn/urtrator/ui.ShowAboutDialog()
        C:/msys64/home/pztrn/GOPATH/src/github.com/pztrn/urtrator/ui/about.go:36 +0x1fe
reflect.Value.call(0x655fa0, 0x6f0ed0, 0x13, 0x6c235f, 0x4, 0x9bf180, 0x0, 0x0, 0xc042072280, 0x676680, ...)
        C:/Go/src/reflect/value.go:434 +0x5cf
reflect.Value.Call(0x655fa0, 0x6f0ed0, 0x13, 0x9bf180, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/reflect/value.go:302 +0xab
github.com/mattn/go-gtk/glib._go_glib_callback(0x37ab2a0)
        C:/msys64/home/pztrn/GOPATH/src/github.com/mattn/go-gtk/glib/glib.go:758 +0x125
github.com/mattn/go-gtk/glib._cgoexpwrap_b00a5877f6a0__go_glib_callback(0x37ab2a0)
        ??:0 +0x32
github.com/mattn/go-gtk/gtk._Cfunc_gtk_main()
        ??:0 +0x48
github.com/mattn/go-gtk/gtk.Main()
        C:/msys64/home/pztrn/GOPATH/src/github.com/mattn/go-gtk/gtk/gtk.go:248 +0x1b
github.com/pztrn/urtrator/ui.(*MainWindow).Initialize(0xc0420845a0)
        C:/msys64/home/pztrn/GOPATH/src/github.com/pztrn/urtrator/ui/mainwindow.go:453 +0xd05
main.main()
        C:/msys64/home/pztrn/GOPATH/src/github.com/pztrn/urtrator/urtrator.go:33 +0x157

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 19 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0420b4f20)
        C:/Go/src/database/sql/sql.go:730 +0x51
created by database/sql.Open
        C:/Go/src/database/sql/sql.go:493 +0x1f0
rax     0x8000bb66611fef13
rbx     0x8
rcx     0x7fff44999ee010ed
rdi     0x487e7d0
rsi     0x8000bb66611fef13
rbp     0x0
rsp     0x23ed78
r8      0x0
r9      0x0
r10     0x48f0970
r11     0x48f6030
r12     0x10
r13     0x1470
r14     0x148
r15     0x23f2f0
rip     0x7ffba3b511d0
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

(urtrator.exe:2812): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 15

(urtrator.exe:2812): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 15

(urtrator.exe:2812): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 15
```
Windows 2k12r2 Standart, MSYS2-MINGW64, gtk+2 2.24.28.

**Comment by mattn** [comment]
Ah, currently SetDocumenters is required to show the dialog. This is my bug. If you want to use before fixes, please call SetDocumenters.

**Comment by pztrn** [comment]
Hm, any particular order of calls needed? https://github.com/pztrn/urtrator/blob/master/ui/about.go and still crashes on Windows and macOS, but works without SetDocumenters on Linux.

**Comment by mattn** [comment]
I figure out the bug. I'll fix in later.

**Comment by mattn** [comment]
Fixed. Could you please try in latest.

**Comment by pztrn** [comment]
Yeah, confirmed as fixed on macOS (can view data on all tabs and no crash), but on Windows application just crashed without any message and exitcode 127.

**Comment by mattn** [comment]
Wtf, the crash occur whlie start-up? or displaying about dialog?

**Comment by pztrn** [comment]
While displaying dialog, of course. Nothing shows at all, but app crashed with exit code 127.

**Comment by mattn** [comment]
Okay, I figure out true problem maybe. And fixed in last change.

**Comment by pztrn** [comment]
Windows (Win2K12R2 amd64 specifically) - all ok
macOS 10.11.6 - all ok
Linux - all ok.

Looks like the problem is fixed :)

**Comment by mattn** [comment]
Thanks
