### ISSUE TITLE
GtkTreeSortable.SetSortFunc not working

### ISSUE THREAD

**Issue by pztrn** [mattn/go-gtk#290]
Looks like some additional conversion should be done, or I'm doing something wrong?

How I call it:

```go
m.all_servers_store_sortable.SetSortFunc(m.column_pos["Servers"]["Ping"], m.sortServersByPing)
```

What I got:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x43a0720, 0xc4202c82c0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/mattn/go-gtk/gtk._cgoCheckPointer0(0xc420408e70, 0x0, 0x0, 0x0, 0x0)
	??:0 +0x59
github.com/mattn/go-gtk/gtk.(*TreeSortable).SetSortFunc(0xc420408e70, 0x6, 0xc4202c82b0)
	/Volumes/DATA/.go/src/github.com/mattn/go-gtk/gtk/gtk.go:4876 +0xdc
github.com/pztrn/urtrator/ui.(*MainWindow).InitializeTabs(0xc42008a000)
	/Volumes/DATA/.go/src/github.com/pztrn/urtrator/ui/mainwindow_init.go:447 +0x843
github.com/pztrn/urtrator/ui.(*MainWindow).Initialize(0xc42008a000)
	/Volumes/DATA/.go/src/github.com/pztrn/urtrator/ui/mainwindow_init.go:115 +0x7ef
main.main()
	/Volumes/DATA/Projects/github/my/urtrator/urtrator.go:33 +0x148
exit status 2
```

`m.sortServersByPing` is identical to gtk.SortFunc (i.e. received params and returning integer).

**Comment by pztrn** [comment]
Not so fixed :(

```
panic: interface conversion: interface {} is **gtk.TreeSortable, not *gtk.TreeSortable

goroutine 1 [running, locked to thread]:
panic(0x43a24a0, 0xc420011700)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/mattn/go-gtk/gtk._go_call_sort_func(0x722e920)
	/Volumes/DATA/.go/src/github.com/mattn/go-gtk/gtk/gtk.go:4884 +0x251
github.com/mattn/go-gtk/gtk._cgoexpwrap_a79e8532d2d4__go_call_sort_func(0x722e920)
	??:0 +0x2b
github.com/mattn/go-gtk/gtk._Cfunc_gtk_main()
	??:0 +0x41
github.com/mattn/go-gtk/gtk.Main()
	/Volumes/DATA/.go/src/github.com/mattn/go-gtk/gtk/gtk.go:248 +0x14
github.com/pztrn/urtrator/ui.(*MainWindow).Initialize(0xc42008a000)
	/Volumes/DATA/.go/src/github.com/pztrn/urtrator/ui/mainwindow_init.go:168 +0xe95
main.main()
	/Volumes/DATA/Projects/github/my/urtrator/urtrator.go:33 +0x148
exit status 2
```

**Comment by pztrn** [comment]
Okay, in SetSortFunc last line should be:

```go
C._gtk_tree_sortable_set_sort_func(ts.GTreeSortable, gint(col), pointer.Save(ts))
```

Just tested and confirming as working :)

**Comment by pztrn** [comment]
Okay, sorry, I lied. It works initially, but after ~5 clicks on column's header (and call to sorting function) I got this:

```
fatal error: bad pointer in write barrier

runtime stack:
runtime.throw(0x43fe7c6, 0x1c)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:566 +0x95
runtime.writebarrierptr_nostore.func1()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/mbarrier.go:168 +0x36
runtime.systemstack(0x7fff5fbff930)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:1079

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:252 fp=0xc42004bae8 sp=0xc42004bae0
runtime.writebarrierptr_nostore(0xc42059e070, 0x28)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/mbarrier.go:168 +0x63 fp=0xc42004bb08 sp=0xc42004bae8
runtime.heapBitsBulkBarrier(0xc42059e060, 0x20)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/mbitmap.go:618 +0xcf fp=0xc42004bb68 sp=0xc42004bb08
runtime.typedmemmove(0x43c1660, 0xc42059e060, 0x7fff5fbfe568)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/mbarrier.go:183 +0x65 fp=0xc42004bba0 sp=0xc42004bb68
github.com/mattn/go-gtk/gtk._go_call_sort_func(0x683e820)
	/Volumes/DATA/.go/src/github.com/mattn/go-gtk/gtk/gtk.go:4888 +0x1e5 fp=0xc42004bbf8 sp=0xc42004bba0
github.com/mattn/go-gtk/gtk._cgoexpwrap_7d7d16b2fc6c__go_call_sort_func(0x683e820)
	??:0 +0x2b fp=0xc42004bc10 sp=0xc42004bbf8
runtime.call32(0x0, 0x7fff5fbfe478, 0x7fff5fbfe518, 0x8)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:479 +0x4c fp=0xc42004bc40 sp=0xc42004bc10
runtime.cgocallbackg1(0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/cgocall.go:283 +0x19d fp=0xc42004bcb8 sp=0xc42004bc40
runtime.cgocallbackg(0x0)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/cgocall.go:170 +0x84 fp=0xc42004bd20 sp=0xc42004bcb8
runtime.cgocallback_gofunc(0x400a6f8, 0x4241310, 0xc42004bdb8, 0x4622100)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:728 +0x74 fp=0xc42004bd40 sp=0xc42004bd20
runtime.asmcgocall(0x4241310, 0xc42004bdb8)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:575 +0x42 fp=0xc42004bd48 sp=0xc42004bd40
runtime.cgocall(0x4241310, 0xc42004bdb8, 0xc400000000)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/cgocall.go:132 +0x128 fp=0xc42004bd88 sp=0xc42004bd48
github.com/mattn/go-gtk/gtk._Cfunc_gtk_main()
	??:0 +0x41 fp=0xc42004bdb8 sp=0xc42004bd88
github.com/mattn/go-gtk/gtk.Main()
	/Volumes/DATA/.go/src/github.com/mattn/go-gtk/gtk/gtk.go:248 +0x14 fp=0xc42004bdc0 sp=0xc42004bdb8
github.com/pztrn/urtrator/ui.(*MainWindow).Initialize(0xc42009e000)
	/Volumes/DATA/.go/src/github.com/pztrn/urtrator/ui/mainwindow_init.go:168 +0xe95 fp=0xc42004bee0 sp=0xc42004bdc0
main.main()
	/Volumes/DATA/Projects/github/my/urtrator/urtrator.go:33 +0x148 fp=0xc42004bf48 sp=0xc42004bee0
runtime.main()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/proc.go:183 +0x1f4 fp=0xc42004bfa0 sp=0xc42004bf48
runtime.goexit()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42004bfa8 sp=0xc42004bfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 20 [chan receive]:
database/sql.(*DB).connectionOpener(0xc4200cd550)
	/usr/local/Cellar/go/1.7.3/libexec/src/database/sql/sql.go:730 +0x4a
created by database/sql.Open
	/usr/local/Cellar/go/1.7.3/libexec/src/database/sql/sql.go:493 +0x1e9
exit status 2
```

**Comment by pztrn** [comment]
This is maybe related to go's gc mechanism or the way how to work with it. with `GOGC=off` (or `runtime.debug.SetGCPercent(-1)`) no crashes occured, despite on clicks count.

**Comment by mattn** [comment]
Ah, sorry. my fault. will fix.

**Comment by pztrn** [comment]
Just for info - compiled Go devel (go version devel +75055de Tue Nov 22 04:28:59 2016 +0000 darwin/amd64) - and no write barrier thing occured. Looks like they fixed it, at least in terms of GC.

**Comment by mattn** [comment]
Could you please try last change?

**Comment by pztrn** [comment]
Yea, no messages about "**gtk.TreeSortable, not *gtk.TreeSortable", but yet write barrier is here on 1.7.3. `GOGC=off` fixes barrier problem, but add a memory ones :)

On devel version of Go everything is perfect, no crashes on sorting.
