### ISSUE TITLE
builder demo about dialog segv

### ISSUE THREAD

**Issue by tedx** [mattn/go-gtk#335]
I just started looking at go gtk support and see this segfault on my RHEL6 box. Is this a known issue? I'm using:
go version go1.7.3 linux/amd64

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7ffcbf8ad000 pc=0x54dd6b]

runtime stack:
runtime.throw(0x5a8367, 0x2a)
	/usr/lib/golang/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/lib/golang/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x543b90, 0xc420051ed8, 0xc400000000)
	/usr/lib/golang/src/runtime/cgocall.go:131 +0x110 fp=0xc420051ea8 sp=0xc420051e68
github.com/mattn/go-gtk/gtk._Cfunc_gtk_main()
	??:0 +0x41 fp=0xc420051ed8 sp=0xc420051ea8
github.com/mattn/go-gtk/gtk.Main()
	/home/tedx/gocode/src/github.com/mattn/go-gtk/gtk/gtk.go:261 +0x14 fp=0xc420051ee0 sp=0xc420051ed8
main.main()
	/home/tedx/gocode/src/github.com/mattn/go-gtk/example/builder/builder.go:25 +0x10a fp=0xc420051f48 sp=0xc420051ee0
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:183 +0x1f4 fp=0xc420051fa0 sp=0xc420051f48
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420051fa8 sp=0xc420051fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2086 +0x1

**Comment by SMerrony** [comment]
Exact same crash with current go version go1.9.2 linux/amd64 on up-to-date Ubuntu.

**Comment by pebbe** [comment]
I get the same with go version go1.10.3 linux/amd64 on up-to-date Debian.
