### ISSUE TITLE
Do not support callback with more than one parameter

### ISSUE THREAD

**Issue by lidaobing** [mattn/go-gtk#364]
for the following testcase:

```go
func TestWindow_ConfigureEvent(t *testing.T) {
	Init(nil)
	w := NewWindow(WINDOW_TOPLEVEL)
	width := 0
	height := 0
	onConfigureEvent := func(window *Window, event *gdk.EventConfigure) {
		width = event.Width
		height = event.Height
		//println(window, event)
	}
	w.Connect("configure-event", onConfigureEvent)
	w.Resize(200, 300)
	w.Emit("configure-event")
	for EventsPending() {
		MainIterationDo(false)
	}
	assert.Equal(t, width, 200)
	assert.Equal(t, height, 300)
}
```

it crashed with
```
=== RUN   TestWindow_ConfigureEvent
--- FAIL: TestWindow_ConfigureEvent (0.00s)
panic: reflect: Call using zero Value argument [recovered]
	panic: reflect: Call using zero Value argument

goroutine 10 [running]:
testing.tRunner.func1(0xc4200fc5a0)
	/usr/local/Cellar/go/1.9.1/libexec/src/testing/testing.go:711 +0x2d2
panic(0x4366f80, 0xc420040f10)
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:491 +0x283
reflect.Value.call(0x43725e0, 0xc4200e04a0, 0x13, 0x43ee07a, 0x4, 0xc420079050, 0x2, 0x2, 0x43e4c80, 0x438f4e0, ...)
	/usr/local/Cellar/go/1.9.1/libexec/src/reflect/value.go:366 +0x1210
reflect.Value.Call(0x43725e0, 0xc4200e04a0, 0x13, 0xc420079050, 0x2, 0x2, 0xd0, 0x3, 0xc420001500)
	/usr/local/Cellar/go/1.9.1/libexec/src/reflect/value.go:302 +0xa4
github.com/mattn/go-gtk/glib._go_glib_callback(0x586b100)
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/glib/glib.go:814 +0x11a
github.com/mattn/go-gtk/glib._cgoexpwrap_fe5c68f3714d__go_glib_callback(0x586b100)
	github.com/mattn/go-gtk/glib/_obj/_cgo_gotypes.go:1837 +0x2b
github.com/mattn/go-gtk/glib._Cfunc__g_signal_emit_by_name(0x6839020, 0x5687f70)
	github.com/mattn/go-gtk/glib/_obj/_cgo_gotypes.go:346 +0x41
github.com/mattn/go-gtk/glib.(*GObject).Emit.func1(0x6839020, 0x5687f70)
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/glib/glib.go:900 +0x6a
github.com/mattn/go-gtk/glib.(*GObject).Emit(0xc42002bef8, 0x43f0a7c, 0xf)
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/glib/glib.go:900 +0x7e
github.com/mattn/go-gtk/gtk.(*Widget).Emit(0xc42000e0e8, 0x43f0a7c, 0xf)
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/gtk/gtk.go:10544 +0x4c
github.com/mattn/go-gtk/gtk.TestWindow_ConfigureEvent(0xc4200fc5a0)
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/gtk/gtk_test.go:119 +0x16a
testing.tRunner(0xc4200fc5a0, 0x4402a50)
	/usr/local/Cellar/go/1.9.1/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.1/libexec/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/mattn/go-gtk/gtk	1.014s
```

**Comment by lidaobing** [comment]
if `t.NumIn() > 1`,  the fargs[1:] is not initialized.

```go
	fargs := make([]reflect.Value, t.NumIn())
	if len(fargs) > 0 {
		fargs[0] = reflect.ValueOf(context)
	}
	ret := context.f.Call(fargs)
```

**Comment by lidaobing** [comment]
I know how to use callback in go-gtk after read the demo, but still some problem in some special event(for example: #368 )
