### ISSUE TITLE
demo crashed

### ISSUE THREAD

**Issue by lidaobing** [mattn/go-gtk#367]
open demo, and click "Help -> About"

```
$ go run example/demo/demo.go
# github.com/mattn/go-gtk/gio
ld: warning: /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation, ignoring unexpected dylib file
# github.com/mattn/go-gtk/gtk
ld: warning: /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation, ignoring unexpected dylib file

(process:64936): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x41063d0]

goroutine 1 [running]:
github.com/mattn/go-gtk/gtk.(*AboutDialog).SetLogo(0xc42000e180, 0x0)
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/gtk/gtk.go:1830 +0x30
main.main.func13()
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/example/demo/demo.go:331 +0x151
reflect.Value.call(0x41d9420, 0x423e6b8, 0x13, 0x42355e8, 0x4, 0x4448a20, 0x0, 0x0, 0x421df40, 0xc420082601, ...)
	/usr/local/Cellar/go/1.9.1/libexec/src/reflect/value.go:434 +0x906
reflect.Value.Call(0x41d9420, 0x423e6b8, 0x13, 0x4448a20, 0x0, 0x0, 0x200000003, 0x3, 0xc420000180)
	/usr/local/Cellar/go/1.9.1/libexec/src/reflect/value.go:302 +0xa4
github.com/mattn/go-gtk/glib._go_glib_callback(0x6097a80)
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/glib/glib.go:814 +0x11a
github.com/mattn/go-gtk/glib._cgoexpwrap_fe5c68f3714d__go_glib_callback(0x6097a80)
	github.com/mattn/go-gtk/glib/_obj/_cgo_gotypes.go:1837 +0x2b
github.com/mattn/go-gtk/gtk._Cfunc_gtk_main()
	github.com/mattn/go-gtk/gtk/_obj/_cgo_gotypes.go:11085 +0x41
github.com/mattn/go-gtk/gtk.Main()
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/gtk/gtk.go:285 +0x20
main.main()
	/Users/lidaobing/go/src/github.com/mattn/go-gtk/example/demo/demo.go:354 +0x1706
exit status 2
```

**Comment by lidaobing** [comment]
I found the reason, I need run demo.go from the dir of demo.go
